default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tunes-takeout_development

test:
  <<: *default
  database: tunes-takeout_test

production:
  <<: *default
  database: tunes-takeout_production
  username: tunes-takeout
  password: <%= ENV['TUNES-TAKEOUT_DATABASE_PASSWORD'] %>
